In [17]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.4.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

In [18]:
import pandas as pd
import numpy as np
import nltk
import joblib

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [19]:
df = pd.read_csv("spam.csv", encoding="latin-1")
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [20]:
df = df[['v1', 'v2']]
df.columns = ['label', 'message']
df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [21]:
df['label'] = df['label'].map({'ham':0, 'spam':1})
df.head()

   label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [22]:
X = df['message']
y = df['label']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [23]:
vectorizer = CountVectorizer()

X_train = vectorizer.fit_transform(X_train)
X_test = vectorizer.transform(X_test)

In [24]:
model = MultinomialNB()

model.fit(X_train, y_train)

MultinomialNB()

In [25]:
prediction = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, prediction))

Accuracy: 0.9838565022421525

In [26]:
message = ["Congratulations! You have won a FREE iPhone. Click here now."]

message = vectorizer.transform(message)

prediction = model.predict(message)

if prediction[0] == 1:
    print("Spam")
else:
    print("Not Spam")

Spam

In [27]:
joblib.dump(model, "spam_model.pkl")
joblib.dump(vectorizer, "vectorizer.pkl")

print("Model saved successfully!")

Model saved successfully!

In [28]:
from google.colab import files

files.download("spam_model.pkl")
files.download("vectorizer.pkl")

In [29]:
%%writefile app.py

import streamlit as st
import joblib

model = joblib.load("spam_model.pkl")
vectorizer = joblib.load("vectorizer.pkl")

st.title("📧 Spam Email Classifier")

message = st.text_area("Enter your email or SMS message")

if st.button("Predict"):
    data = vectorizer.transform([message])
    prediction = model.predict(data)

    if prediction[0] == 1:
        st.error("🚫 Spam Message")
    else:
        st.success("✅ Not Spam")

Writing app.py

In [30]:
%%writefile requirements.txt
streamlit
pandas
numpy
scikit-learn
joblib
nltk

Writing requirements.txt

In [31]:
%%writefile README.md
# Spam Email Classifier

## Overview
This project uses Machine Learning to classify SMS or Email messages as Spam or Not Spam.

## Technologies Used
- Python
- Pandas
- Scikit-learn
- NLTK
- Streamlit

## Machine Learning Algorithm
- CountVectorizer
- Multinomial Naive Bayes

## Accuracy
98%

## Features
- Spam Detection
- Simple User Interface
- Fast Prediction

## How to Run

pip install -r requirements.txt

streamlit run app.py

Writing README.md

In [32]:
from google.colab import files

files.download("app.py")
files.download("README.md")
files.download("requirements.txt")
files.download("spam_model.pkl")
files.download("vectorizer.pkl")